language: python

python:
    - "2.7"

install:
    "pip install -r requerimientos.txt"

before_script:
    - autopep8 -ir *
    - flake8 --max-complexity=5 --exclude=*.txt,*.md,*

script:
    - cd tests/features
    - python TestCalculadora.py
    - coverage run --branch TestCalculadora.py
    - cd ..
    - lettuce
    - echo "Ya no me deja hacer push :("
